### ISSUE TITLE
Please move to Launch Library 2 or archive this repo

### ISSUE THREAD

**Issue by Nosudrum** [arekminajj/LaunchLibraryNET#2]
As stated on the Launch Library website since early 2020, support for the API provided from the launchlibrary.net URL has come to an end and the API will be closing down on December 31, 2020.
Starting November 1 there will be a launch asking to move to its successor : Launch Library 2.

If you intend to switch to the new API, you can find more details on The Space Devs website and Discord server:
https://thespacedevs.com/
https://discord.gg/p7ntkNA

Otherwise, please archive this repo or state clearly that it is no longer usable.

Thanks a lot,

The Space Devs team

**Comment by arekminajj** [comment]
Hey, this project uses Launch Library 2. I didn't work on it for a bit and the project is not done yet, but still, it uses Launch Library 2.
https://github.com/arekminajj/LaunchLibraryNET/blob/0301d05671867ac78675be4833915b95367f9283/LaunchLibraryNET/Client.cs#L11

**Comment by Nosudrum** [comment]
Okay perfect ! 👍 
Good luck with your project and don't forget to join the discord server to stay updated or if you have any question :)
